// Decompiled with JetBrains decompiler
// Type: Microsoft.Xna.Framework.GamerServices.GamerPresenceMode
// Assembly: Microsoft.Xna.Framework.GamerServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553
// MVID: 4CE9CD1E-CFF0-4A29-B8E1-5772070CE886
// Assembly location: C:\Users\Empyreal96\Desktop\WINDOW~1\100~1.150\MICROS~2.CBS\ARM_MI~1.297\windows\System32\MI5CF0~1.DLL

namespace Microsoft.Xna.Framework.GamerServices
{
  public enum GamerPresenceMode
  {
    None,
    SinglePlayer,
    Multiplayer,
    LocalCoOp,
    LocalVersus,
    OnlineCoOp,
    OnlineVersus,
    VersusComputer,
    Stage,
    Level,
    CoOpStage,
    CoOpLevel,
    ArcadeMode,
    CampaignMode,
    ChallengeMode,
    ExplorationMode,
    PracticeMode,
    PuzzleMode,
    ScenarioMode,
    StoryMode,
    SurvivalMode,
    TutorialMode,
    DifficultyEasy,
    DifficultyMedium,
    DifficultyHard,
    DifficultyExtreme,
    Score,
    VersusScore,
    Winning,
    Losing,
    ScoreIsTied,
    Outnumbered,
    OnARoll,
    InCombat,
    BattlingBoss,
    TimeAttack,
    TryingForRecord,
    FreePlay,
    WastingTime,
    StuckOnAHardBit,
    NearlyFinished,
    LookingForGames,
    WaitingForPlayers,
    WaitingInLobby,
    SettingUpMatch,
    PlayingWithFriends,
    AtMenu,
    StartingGame,
    Paused,
    GameOver,
    WonTheGame,
    ConfiguringSettings,
    CustomizingPlayer,
    EditingLevel,
    InGameStore,
    WatchingCutscene,
    WatchingCredits,
    PlayingMinigame,
    FoundSecret,
    CornflowerBlue,
  }
}
