// Decompiled with JetBrains decompiler
// Type: Microsoft.Xna.Framework.GamerServices.Stub.GSPropertyName
// Assembly: Microsoft.Xna.Framework.GamerServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553
// MVID: 4CE9CD1E-CFF0-4A29-B8E1-5772070CE886
// Assembly location: C:\Users\Empyreal96\Desktop\WINDOW~1\100~1.150\MICROS~2.CBS\ARM_MI~1.297\windows\System32\MI5CF0~1.DLL

namespace Microsoft.Xna.Framework.GamerServices.Stub
{
  internal enum GSPropertyName
  {
    None,
    GamerHandle,
    PlayerIndex,
    Gamertag,
    DisplayName,
    SignInState,
    IsGuest,
    PrivilegeOptions,
    Motto,
    Reputation,
    GamerZone,
    Culture,
    GamerScore,
    TitlePlayed,
    TotalAchievements,
    GamerPicture,
    PartySize,
    AccelerateWithButtons,
    AutoAim,
    AutoCenter,
    BrakeWithButtons,
    ControllerSensitivity,
    GameDifficulty,
    InvertYAxis,
    ManualTransmission,
    MoveWithRightThumbStick,
    PrimaryColor,
    RacingCameraAngle,
    SecondaryColor,
    FriendRequestReceivedFrom,
    FriendRequestSentTo,
    HasVoice,
    InviteAccepted,
    InviteReceivedFrom,
    InviteRejected,
    InviteSentTo,
    IsAway,
    IsBusy,
    IsJoinable,
    IsOnline,
    IsPlaying,
    Presence,
    AchievementKey,
    AchievementName,
    AchievementDescription,
    AchievementGamerScore,
    AchievementHowToEarn,
    AchievementIsEarned,
    AchievementEarnedOnline,
    AchievementDisplayBeforeEarned,
    AchievementEarnedDateTime,
    AchievementPicture,
    LeaderboardGamer,
    LeaderboardRank,
    LeaderboardScore,
    LeaderboardRating,
    LeaderboardTime,
    LeaderboardOutcome,
    LeaderboardScoreBlob,
    LeaderboardTimeBlob,
    LeaderboardTimeStamp,
    LeaderboardBestScore,
    LeaderboardBestTime,
    LeaderboardCumulativeScore,
    LeaderboardCumulativeTime,
    LeaderboardGamesPlayed,
    LeaderboardAverageScore,
    LeaderboardAverageTime,
    LeaderboardWins,
    LeaderboardLosses,
    LeaderboardBestScoreBlob,
    LeaderboardBestTimeBlob,
    LeaderboardLastPlayedDateTime,
  }
}
